[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "plastinka-photoassistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "python-dotenv>=1.0.0",
    "ipykernel>=6.30.1",
    "joblib==1.4.2",
    "numpy~=1.26.4",
    "pyyaml==6.0.2",
    "roboflow>=1.2.6",
    "scikit-learn~=1.5.1",
    "streamlit==1.37.1",
    "streamlit-authenticator>=0.3.3",
    "torch==2.3.1",
    "torchvision==0.18.1",
    "ultralytics==8.2.88",
    "lightning==2.1.0",
    "extra-streamlit-components>=0.1.71",
]

[project.scripts]
plastinka = "main:start"

[tool.setuptools]
packages = ["photoassist", "user_interface"]
py-modules = ["main"]

[tool.uv.pip]
torch-backend = "auto"
